global:
  marketplace-ami: false
  owner: mick.casper@waterfield.com
  qsname: connect-integration-smg-agenttrack
  regions:
    - us-east-1
  reporting: true
 
tests:
  connect-integration-smg-agenttrackt1:
    parameter_input: defaults.json
    template_file: agenttrack.json
